# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "development" ]

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
    - name: Build & Test
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Clean install of dependencies
      run: npm ci
    - name: Build application
      run: npm run build --if-present
    - name: Run test
      run: npm run test:prod
    - name: Set up git config
      run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
    - name: Update version
      run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          npm version prerelease -m "Upgrade to %s [no ci]"
          git push
    - run: |
        echo "APP_VERSION=$(npm pkg get version)" >> $GITHUB_ENV
    - run: echo "Updated application to version ${{ env.APP_VERSION }}."
    - name: Deploy to DEV
      run: echo "Successfully deployed to DEV-Environment."
