on:
  push:
    branches: [ "development" ]

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build & Test
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Clean install of dependencies
      run: npm ci
    - name: Build application
      run: npm run build --if-present
    - name: Run test
      run: npm run test:prod
    - name: Update version
      run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          npm version prerelease -m "Upgrade to %s"
          echo "APP_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          git push --follow-tags
    - run: echo "Updated application to version ${{ env.APP_VERSION }}."
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.APP_VERSION }}
        release_name: Release ${{ env.APP_VERSION }}
        body: |
          Release ${{ env.APP_VERSION }}
        draft: false
        prerelease: true
    - name: Deploy to DEV
      run: echo "Successfully deployed to DEV-Environment."
